
<a href="<?php
echo $this->url(
        array('controller' => 'employee', 'action' => 'new'), 'default', true)
?>">Add New Employee</a>

<table id="employee_list_table">
    <tr>
        <th>Email</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>ID</th>
    </tr>

    <?php foreach ($this->entries as $entry): ?>
        <tr>
            <td><a href="<?php
                echo $this->url(
                        array('controller' => 'employee',
                    'action' => 'edit',
                    'id' => $this->escape($entry->employeeid)), 'default', true)
                ?>"><?php echo $this->escape($entry->email) ?></a></td>
            <td><?php echo $this->escape($entry->firstname) ?></td>
            <td><?php echo $this->escape($entry->lastname) ?></td>
            <td><?php echo $this->escape($entry->employeeid) ?></td>
        </tr>
    <?php endforeach ?>

</table>